
import java.awt.Color;
import java.util.HashSet;
import java.util.List;
import java.io.*;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FilenameFilter;
import java.util.ArrayList;
import java.util.TreeSet;
import mdlaf.MaterialLookAndFeel;
import mdlaf.utils.MaterialColors;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sinny
 */
public class Menu extends javax.swing.JFrame {
private final Timetable timetable;
private final String[] dayDict = {"Monday","Tuesday","Wednesday","Thursday","Friday"};
    /**
     * Creates new form Menu
     *
     * @param tt
     */
    public Menu(Timetable tt) {
        initComponents();
        getContentPane().setBackground(new Color(53,59,72));
        timetable = tt;
        home.doClick();
    }
    private void BtnHover(JButton j1)
    {
        Color c1, c2;
        c1 = j1.getBackground();
        c2 = j1.getForeground();
        j1.setBackground(c2);
        j1.setForeground(c1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeachersDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeachersAvailableList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TeachersSelectedList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Createbtn = new javax.swing.JButton();
        CoursesDialog = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        CoursesAvailableList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        CoursesSelectedList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        Createbtn1 = new javax.swing.JButton();
        SectionsDialog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        SectionsAvailableList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SectionsSelectedList = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        Createbtn2 = new javax.swing.JButton();
        ClashesDialog = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        Data = new javax.swing.JTextArea();
        Return = new javax.swing.JButton();
        QueriesTeachers = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        QueriesTeachersAvailable = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        QueriesTeachersSelected = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        Createbtn3 = new javax.swing.JButton();
        QueriesSections = new javax.swing.JDialog();
        jScrollPane11 = new javax.swing.JScrollPane();
        QueriesSectionsAvailable = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        QueriesSectionsSelected = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        Createbtn4 = new javax.swing.JButton();
        QueriesRoom = new javax.swing.JDialog();
        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnPanel2 = new javax.swing.JPanel();
        timetables = new javax.swing.JButton();
        btnPanel1 = new javax.swing.JPanel();
        queries = new javax.swing.JButton();
        btnPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        menuparent = new javax.swing.JPanel();
        menuHome = new javax.swing.JPanel();
        menuQueries = new javax.swing.JPanel();
        freeSectionsBtn = new javax.swing.JButton();
        freeTeachersBtn = new javax.swing.JButton();
        freeSlotsBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        QueriesOutput = new javax.swing.JTextArea();
        menuTimetables = new javax.swing.JPanel();
        TeachersButton = new javax.swing.JButton();
        SectionsButton = new javax.swing.JButton();
        CoursesButton = new javax.swing.JButton();

        TeachersDialog.setBackground(new java.awt.Color(53, 59, 72));
        TeachersDialog.setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        TeachersDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        TeachersAvailableList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        TeachersAvailableList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeachersAvailableList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TeachersAvailableListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(TeachersAvailableList);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Hold CTRL to select multiple option(s)");

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Available");

        TeachersSelectedList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        TeachersSelectedList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeachersSelectedList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                TeachersSelectedListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(TeachersSelectedList);

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Selected");

        Createbtn.setBackground(new java.awt.Color(47, 54, 64));
        Createbtn.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Createbtn.setForeground(new java.awt.Color(245, 246, 250));
        Createbtn.setText("Create");
        Createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TeachersDialogLayout = new javax.swing.GroupLayout(TeachersDialog.getContentPane());
        TeachersDialog.getContentPane().setLayout(TeachersDialogLayout);
        TeachersDialogLayout.setHorizontalGroup(
            TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersDialogLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TeachersDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(TeachersDialogLayout.createSequentialGroup()
                        .addGroup(TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(TeachersDialogLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        TeachersDialogLayout.setVerticalGroup(
            TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeachersDialogLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TeachersDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        CoursesDialog.setBackground(new java.awt.Color(53, 59, 72));
        CoursesDialog.setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        CoursesDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CoursesAvailableList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        CoursesAvailableList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CoursesAvailableList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                CoursesAvailableListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(CoursesAvailableList);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Hold CTRL to select multiple option(s)");

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Available");

        CoursesSelectedList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        CoursesSelectedList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane4.setViewportView(CoursesSelectedList);

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selected");

        Createbtn1.setBackground(new java.awt.Color(47, 54, 64));
        Createbtn1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Createbtn1.setForeground(new java.awt.Color(245, 246, 250));
        Createbtn1.setText("Create");
        Createbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Createbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CoursesDialogLayout = new javax.swing.GroupLayout(CoursesDialog.getContentPane());
        CoursesDialog.getContentPane().setLayout(CoursesDialogLayout);
        CoursesDialogLayout.setHorizontalGroup(
            CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursesDialogLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CoursesDialogLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CoursesDialogLayout.createSequentialGroup()
                        .addGroup(CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(CoursesDialogLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Createbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        CoursesDialogLayout.setVerticalGroup(
            CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CoursesDialogLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CoursesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        SectionsDialog.setBackground(new java.awt.Color(53, 59, 72));
        SectionsDialog.setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        SectionsDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        SectionsAvailableList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        SectionsAvailableList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SectionsAvailableList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                SectionsAvailableListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(SectionsAvailableList);

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Hold CTRL to select multiple option(s)");

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Available");

        SectionsSelectedList.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        SectionsSelectedList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane6.setViewportView(SectionsSelectedList);

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Selected");

        Createbtn2.setBackground(new java.awt.Color(47, 54, 64));
        Createbtn2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Createbtn2.setForeground(new java.awt.Color(245, 246, 250));
        Createbtn2.setText("Create");
        Createbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Createbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SectionsDialogLayout = new javax.swing.GroupLayout(SectionsDialog.getContentPane());
        SectionsDialog.getContentPane().setLayout(SectionsDialogLayout);
        SectionsDialogLayout.setHorizontalGroup(
            SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectionsDialogLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SectionsDialogLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SectionsDialogLayout.createSequentialGroup()
                        .addGroup(SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(SectionsDialogLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Createbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        SectionsDialogLayout.setVerticalGroup(
            SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectionsDialogLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SectionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ClashesDialog.setAlwaysOnTop(true);
        ClashesDialog.setBounds(new java.awt.Rectangle(0, 0, 700, 400));

        Data.setColumns(20);
        Data.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        Data.setRows(5);
        Data.setFocusable(false);
        jScrollPane7.setViewportView(Data);

        Return.setText("OK");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClashesDialogLayout = new javax.swing.GroupLayout(ClashesDialog.getContentPane());
        ClashesDialog.getContentPane().setLayout(ClashesDialogLayout);
        ClashesDialogLayout.setHorizontalGroup(
            ClashesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClashesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClashesDialogLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
        ClashesDialogLayout.setVerticalGroup(
            ClashesDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClashesDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Return, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        QueriesTeachers.setBackground(new java.awt.Color(53, 59, 72));
        QueriesTeachers.setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        QueriesTeachers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        QueriesTeachersAvailable.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        QueriesTeachersAvailable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QueriesTeachersAvailable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                QueriesTeachersAvailableValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(QueriesTeachersAvailable);

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setText("Hold CTRL to select multiple option(s)");

        jLabel12.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Available");

        QueriesTeachersSelected.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        QueriesTeachersSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane9.setViewportView(QueriesTeachersSelected);

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Selected");

        Createbtn3.setBackground(new java.awt.Color(47, 54, 64));
        Createbtn3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Createbtn3.setForeground(new java.awt.Color(245, 246, 250));
        Createbtn3.setText("Create");
        Createbtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Createbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Createbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QueriesTeachersLayout = new javax.swing.GroupLayout(QueriesTeachers.getContentPane());
        QueriesTeachers.getContentPane().setLayout(QueriesTeachersLayout);
        QueriesTeachersLayout.setHorizontalGroup(
            QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesTeachersLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QueriesTeachersLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(QueriesTeachersLayout.createSequentialGroup()
                        .addGroup(QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(QueriesTeachersLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Createbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        QueriesTeachersLayout.setVerticalGroup(
            QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesTeachersLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        QueriesSections.setBackground(new java.awt.Color(53, 59, 72));
        QueriesSections.setBounds(new java.awt.Rectangle(0, 0, 700, 500));
        QueriesSections.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        QueriesSections.setFocusTraversalPolicyProvider(true);

        QueriesSectionsAvailable.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        QueriesSectionsAvailable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QueriesSectionsAvailable.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                QueriesSectionsAvailableValueChanged(evt);
            }
        });
        jScrollPane11.setViewportView(QueriesSectionsAvailable);

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setText("Hold CTRL to select multiple option(s)");

        jLabel15.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Available");

        QueriesSectionsSelected.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        QueriesSectionsSelected.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane12.setViewportView(QueriesSectionsSelected);

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Selected");

        Createbtn4.setBackground(new java.awt.Color(47, 54, 64));
        Createbtn4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Createbtn4.setForeground(new java.awt.Color(245, 246, 250));
        Createbtn4.setText("Create");
        Createbtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Createbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Createbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QueriesSectionsLayout = new javax.swing.GroupLayout(QueriesSections.getContentPane());
        QueriesSections.getContentPane().setLayout(QueriesSectionsLayout);
        QueriesSectionsLayout.setHorizontalGroup(
            QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesSectionsLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QueriesSectionsLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(QueriesSectionsLayout.createSequentialGroup()
                        .addGroup(QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(117, 117, 117))))
            .addGroup(QueriesSectionsLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(Createbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        QueriesSectionsLayout.setVerticalGroup(
            QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueriesSectionsLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(QueriesSectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Createbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout QueriesRoomLayout = new javax.swing.GroupLayout(QueriesRoom.getContentPane());
        QueriesRoom.getContentPane().setLayout(QueriesRoomLayout);
        QueriesRoomLayout.setHorizontalGroup(
            QueriesRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        QueriesRoomLayout.setVerticalGroup(
            QueriesRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(53, 59, 72));
        setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        setName("Menu"); // NOI18N
        setResizable(false);

        bg.setBackground(new java.awt.Color(53, 59, 72));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(63, 81, 181));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoPanel.setBackground(new java.awt.Color(63, 81, 181));
        logoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/title.png"))); // NOI18N
        jLabel10.setIconTextGap(0);
        jLabel10.setPreferredSize(new java.awt.Dimension(190, 80));
        logoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 200, 80));

        sidepanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 80));

        btnPanel2.setBackground(new java.awt.Color(63, 81, 181));

        timetables.setBackground(new java.awt.Color(63, 81, 181));
        timetables.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        timetables.setForeground(new java.awt.Color(232, 234, 246));
        timetables.setText("Custom Timetables");
        timetables.setBorderPainted(false);
        timetables.setContentAreaFilled(false);
        timetables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetables.setFocusPainted(false);
        timetables.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timetables.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                timetablesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                timetablesFocusLost(evt);
            }
        });
        timetables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timetablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timetablesMouseExited(evt);
            }
        });
        timetables.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetablesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanel2Layout = new javax.swing.GroupLayout(btnPanel2);
        btnPanel2.setLayout(btnPanel2Layout);
        btnPanel2Layout.setHorizontalGroup(
            btnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel2Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(timetables, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPanel2Layout.setVerticalGroup(
            btnPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(timetables, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidepanel.add(btnPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, 40));

        btnPanel1.setBackground(new java.awt.Color(63, 81, 181));

        queries.setBackground(new java.awt.Color(63, 81, 181));
        queries.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        queries.setForeground(new java.awt.Color(232, 234, 246));
        queries.setText("Simple Queries");
        queries.setBorderPainted(false);
        queries.setContentAreaFilled(false);
        queries.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        queries.setFocusPainted(false);
        queries.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        queries.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                queriesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                queriesFocusLost(evt);
            }
        });
        queries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                queriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                queriesMouseExited(evt);
            }
        });
        queries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queriesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanel1Layout = new javax.swing.GroupLayout(btnPanel1);
        btnPanel1.setLayout(btnPanel1Layout);
        btnPanel1Layout.setHorizontalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(queries, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPanel1Layout.setVerticalGroup(
            btnPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(queries, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidepanel.add(btnPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        btnPanel3.setBackground(new java.awt.Color(63, 81, 181));

        home.setBackground(new java.awt.Color(63, 81, 181));
        home.setFont(new java.awt.Font("Roboto Medium", 0, 20)); // NOI18N
        home.setForeground(new java.awt.Color(232, 234, 246));
        home.setText("Home");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setFocusPainted(false);
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                homeFocusLost(evt);
            }
        });
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanel3Layout = new javax.swing.GroupLayout(btnPanel3);
        btnPanel3.setLayout(btnPanel3Layout);
        btnPanel3Layout.setHorizontalGroup(
            btnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel3Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnPanel3Layout.setVerticalGroup(
            btnPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sidepanel.add(btnPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 220, 40));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        menuparent.setLayout(new java.awt.CardLayout());

        menuHome.setBackground(new java.awt.Color(53, 59, 72));

        javax.swing.GroupLayout menuHomeLayout = new javax.swing.GroupLayout(menuHome);
        menuHome.setLayout(menuHomeLayout);
        menuHomeLayout.setHorizontalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        menuHomeLayout.setVerticalGroup(
            menuHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        menuparent.add(menuHome, "card4");

        menuQueries.setBackground(new java.awt.Color(53, 59, 72));

        freeSectionsBtn.setBackground(new java.awt.Color(63, 81, 181));
        freeSectionsBtn.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        freeSectionsBtn.setForeground(new java.awt.Color(232, 234, 246));
        freeSectionsBtn.setText("Section free at");
        freeSectionsBtn.setToolTipText("Press to find sections with free timeslots");
        freeSectionsBtn.setBorderPainted(false);
        freeSectionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        freeSectionsBtn.setFocusable(false);
        freeSectionsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                freeSectionsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                freeSectionsBtnMouseExited(evt);
            }
        });
        freeSectionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeSectionsBtnActionPerformed(evt);
            }
        });

        freeTeachersBtn.setBackground(new java.awt.Color(83, 109, 254));
        freeTeachersBtn.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        freeTeachersBtn.setForeground(new java.awt.Color(232, 234, 246));
        freeTeachersBtn.setText("Teachers free at");
        freeTeachersBtn.setToolTipText("Press to find teachers with free timeslots");
        freeTeachersBtn.setBorderPainted(false);
        freeTeachersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        freeTeachersBtn.setFocusable(false);
        freeTeachersBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        freeTeachersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                freeTeachersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                freeTeachersBtnMouseExited(evt);
            }
        });
        freeTeachersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeTeachersBtnActionPerformed(evt);
            }
        });

        freeSlotsBtn.setBackground(new java.awt.Color(124, 77, 255));
        freeSlotsBtn.setFont(new java.awt.Font("Coolvetica Rg", 0, 18)); // NOI18N
        freeSlotsBtn.setForeground(new java.awt.Color(237, 231, 246));
        freeSlotsBtn.setText("Unoccupied slots");
        freeSlotsBtn.setToolTipText("Press to print the unoccupied slots");
        freeSlotsBtn.setBorderPainted(false);
        freeSlotsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        freeSlotsBtn.setFocusable(false);
        freeSlotsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                freeSlotsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                freeSlotsBtnMouseExited(evt);
            }
        });
        freeSlotsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeSlotsBtnActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(53, 59, 72));

        QueriesOutput.setBackground(new java.awt.Color(250, 250, 250));
        QueriesOutput.setColumns(20);
        QueriesOutput.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        QueriesOutput.setForeground(new java.awt.Color(33, 33, 33));
        QueriesOutput.setRows(5);
        jScrollPane10.setViewportView(QueriesOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane10)
                .addContainerGap())
        );

        javax.swing.GroupLayout menuQueriesLayout = new javax.swing.GroupLayout(menuQueries);
        menuQueries.setLayout(menuQueriesLayout);
        menuQueriesLayout.setHorizontalGroup(
            menuQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuQueriesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(menuQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(freeSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(freeTeachersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(freeSectionsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuQueriesLayout.setVerticalGroup(
            menuQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuQueriesLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(freeTeachersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(freeSectionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(freeSlotsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuparent.add(menuQueries, "card2");

        menuTimetables.setBackground(new java.awt.Color(53, 59, 72));

        TeachersButton.setBackground(new java.awt.Color(255, 87, 34));
        TeachersButton.setFont(new java.awt.Font("Coolvetica Rg", 0, 26)); // NOI18N
        TeachersButton.setForeground(new java.awt.Color(251, 233, 231));
        TeachersButton.setText("Teachers Wise");
        TeachersButton.setBorderPainted(false);
        TeachersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TeachersButton.setFocusable(false);
        TeachersButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TeachersButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TeachersButtonMouseExited(evt);
            }
        });
        TeachersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersButtonActionPerformed(evt);
            }
        });

        SectionsButton.setBackground(new java.awt.Color(92, 107, 192));
        SectionsButton.setFont(new java.awt.Font("Coolvetica Rg", 0, 26)); // NOI18N
        SectionsButton.setForeground(new java.awt.Color(232, 234, 246));
        SectionsButton.setText("Sections Wise");
        SectionsButton.setBorderPainted(false);
        SectionsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SectionsButton.setFocusable(false);
        SectionsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SectionsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SectionsButtonMouseExited(evt);
            }
        });
        SectionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionsButtonActionPerformed(evt);
            }
        });

        CoursesButton.setBackground(new java.awt.Color(126, 87, 194));
        CoursesButton.setFont(new java.awt.Font("Coolvetica Rg", 0, 26)); // NOI18N
        CoursesButton.setForeground(new java.awt.Color(237, 231, 246));
        CoursesButton.setText("Courses Wise");
        CoursesButton.setBorderPainted(false);
        CoursesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CoursesButton.setFocusable(false);
        CoursesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CoursesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CoursesButtonMouseExited(evt);
            }
        });
        CoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuTimetablesLayout = new javax.swing.GroupLayout(menuTimetables);
        menuTimetables.setLayout(menuTimetablesLayout);
        menuTimetablesLayout.setHorizontalGroup(
            menuTimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTimetablesLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(menuTimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        menuTimetablesLayout.setVerticalGroup(
            menuTimetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTimetablesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(TeachersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(CoursesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(SectionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        menuparent.add(menuTimetables, "card3");

        bg.add(menuparent, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 680, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TeachersAvailableListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TeachersAvailableListValueChanged
            if(!evt.getValueIsAdjusting())
            {
                List<String> Selections = TeachersAvailableList.getSelectedValuesList();
                DefaultListModel selectedList = new DefaultListModel();
                for(int i=0;i<Selections.size();i++)
                {
                    selectedList.addElement(Selections.get(i));
                }
                TeachersSelectedList.setModel(selectedList);
                
            }
    }//GEN-LAST:event_TeachersAvailableListValueChanged

    private void TeachersSelectedListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_TeachersSelectedListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TeachersSelectedListValueChanged

    private void CreatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatebtnActionPerformed
        HashSet<String> teachers = new HashSet<String>(TeachersAvailableList.getSelectedValuesList());
        final JFileChooser fc = new JFileChooser("D:\\University\\Semester 3\\DSA\\Project\\ModularTable");
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Files",".xlsx"));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Save the timetable file");
        fc.setSelectedFile(new File("TeachersTimetable.xlsx"));
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        int returnVal = fc.showSaveDialog(this);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        ArrayList<CellList> Clashes = new ArrayList<>();
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
                System.out.println(teachers.size());
                timetable.writeTeachersTimetable(fc.getSelectedFile().toString(), teachers);
                TeachersDialog.dispose();
        }
    }//GEN-LAST:event_CreatebtnActionPerformed

    private void Createbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Createbtn1ActionPerformed
        HashSet<String> courses = new HashSet<String>(CoursesAvailableList.getSelectedValuesList());
        final JFileChooser fc = new JFileChooser("D:\\University\\Semester 3\\DSA\\Project\\ModularTable");
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Files",".xlsx"));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Save the timetable file");
        fc.setSelectedFile(new File("CoursesTimetable.xlsx"));
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        int returnVal = fc.showSaveDialog(this);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        ArrayList<CellList> Clashes = new ArrayList<>();
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
                System.out.println(courses.size());
                timetable.writeCoursesTimetable(fc.getSelectedFile().toString(), courses);
                CoursesDialog.dispose();
        }
    }//GEN-LAST:event_Createbtn1ActionPerformed

    private void CoursesAvailableListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_CoursesAvailableListValueChanged
        if(!evt.getValueIsAdjusting())
        {
            List<String> Selections = CoursesAvailableList.getSelectedValuesList();
            DefaultListModel selectedList = new DefaultListModel();
            for(int i=0;i<Selections.size();i++)
            {
                selectedList.addElement(Selections.get(i));
            }
            CoursesSelectedList.setModel(selectedList);

        }
    }//GEN-LAST:event_CoursesAvailableListValueChanged

    private void SectionsAvailableListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_SectionsAvailableListValueChanged
        if(!evt.getValueIsAdjusting())
        {
            List<String> Selections = SectionsAvailableList.getSelectedValuesList();
            DefaultListModel selectedList = new DefaultListModel();
            for(int i=0;i<Selections.size();i++)
            {
                selectedList.addElement(Selections.get(i));
            }
            SectionsSelectedList.setModel(selectedList);
        }
        
    }//GEN-LAST:event_SectionsAvailableListValueChanged

    private void Createbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Createbtn2ActionPerformed
        HashSet<String> sections = new HashSet<>(SectionsAvailableList.getSelectedValuesList());
        final JFileChooser fc = new JFileChooser("D:\\University\\Semester 3\\DSA\\Project\\ModularTable");
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("Files",".xlsx"));
        fc.setAcceptAllFileFilterUsed(false);
        fc.setDialogTitle("Save the timetable file");
        fc.setSelectedFile(new File("SectionsTimetable.xlsx"));
        fc.setDialogType(JFileChooser.SAVE_DIALOG);
        int returnVal = fc.showSaveDialog(this);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        ArrayList<CellList> Clashes = new ArrayList<>();
        if(returnVal == JFileChooser.APPROVE_OPTION)
        {
                System.out.println(sections.size());
                timetable.writeSectionsTimetable(fc.getSelectedFile().toString(), sections);
                SectionsDialog.dispose();
        }
        
        
    }//GEN-LAST:event_Createbtn2ActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ReturnActionPerformed

    private void timetablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetablesMouseEntered
        btnPanel2.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_timetablesMouseEntered

    private void timetablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetablesMouseExited
        btnPanel2.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_timetablesMouseExited

    private void queriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queriesMouseEntered
        btnPanel1.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_queriesMouseEntered

    private void queriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_queriesMouseExited
        btnPanel1.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_queriesMouseExited

    private void queriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queriesActionPerformed
        menuparent.removeAll();
        menuparent.add(menuQueries);
        menuparent.repaint();
        menuparent.revalidate();
        home.setForeground(new Color(232,234,246));
        queries.setForeground(new Color(244, 67, 54));
        timetables.setForeground(new Color(232,234,246));
    }//GEN-LAST:event_queriesActionPerformed

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        btnPanel3.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        btnPanel3.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_homeMouseExited

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        menuparent.removeAll();
        menuparent.add(menuHome);
        menuparent.repaint();
        menuparent.revalidate();
        home.setForeground(new Color(244, 67, 54));
        queries.setForeground(new Color(232,234,246));
        timetables.setForeground(new Color(232,234,246));
    }//GEN-LAST:event_homeActionPerformed

    private void timetablesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetablesActionPerformed
        menuparent.removeAll();
        menuparent.add(menuTimetables);
        menuparent.repaint();
        menuparent.revalidate();
        home.setForeground(new Color(232,234,246));
        queries.setForeground(new Color(232,234,246));
        timetables.setForeground(new Color(244, 67, 54));
    }//GEN-LAST:event_timetablesActionPerformed

    private void TeachersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersButtonActionPerformed
        DefaultListModel list = new DefaultListModel();
        TreeSet<String> teachers = timetable.getTeachers();
        for(String s : teachers)
        {
            list.addElement(s);
        }
        TeachersAvailableList.setModel(list);
        TeachersAvailableList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        TeachersDialog.setLocationRelativeTo(null);
        TeachersDialog.setVisible(true);
    }//GEN-LAST:event_TeachersButtonActionPerformed

    private void CoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesButtonActionPerformed
        DefaultListModel list = new DefaultListModel();
        TreeSet<String> courses = new TreeSet<>(timetable.getCourses());
        
        for(String s : courses)
        {
            list.addElement(s);
        }
        CoursesAvailableList.setModel(list);
        CoursesAvailableList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        CoursesDialog.setLocationRelativeTo(null);
        CoursesDialog.setVisible(true);
    }//GEN-LAST:event_CoursesButtonActionPerformed

    private void SectionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionsButtonActionPerformed
        DefaultListModel list = new DefaultListModel();
        TreeSet<String> sections = new TreeSet<>(timetable.getSections());
        
        for(String s : sections)
        {
            list.addElement(s);
        }
        SectionsAvailableList.setModel(list);
        SectionsAvailableList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        SectionsDialog.setLocationRelativeTo(null);
        SectionsDialog.setVisible(true);
    }//GEN-LAST:event_SectionsButtonActionPerformed

    private void queriesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_queriesFocusGained
        queries.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_queriesFocusGained

    private void timetablesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timetablesFocusGained
        timetables.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_timetablesFocusGained

    private void homeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusGained
        home.setBackground(new Color(53,59,72));
    }//GEN-LAST:event_homeFocusGained

    private void homeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeFocusLost
        home.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_homeFocusLost

    private void queriesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_queriesFocusLost
        queries.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_queriesFocusLost

    private void timetablesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_timetablesFocusLost
        home.setBackground(new Color(53,59,72));
        queries.setBackground(new Color(63,81,181));
        timetables.setBackground(new Color(63,81,181));
    }//GEN-LAST:event_timetablesFocusLost

    private void freeSectionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeSectionsBtnActionPerformed
        DefaultListModel list = new DefaultListModel();
        TreeSet<String> sections = new TreeSet<>(timetable.getSections());
        
        for(String s : sections)
        {
            list.addElement(s);
        }
        QueriesSectionsAvailable.setModel(list);
        QueriesSectionsAvailable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        QueriesSections.setLocationRelativeTo(null);
        QueriesSections.setVisible(true);
    }//GEN-LAST:event_freeSectionsBtnActionPerformed

    private void freeTeachersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeTeachersBtnActionPerformed
        DefaultListModel list = new DefaultListModel();
        TreeSet<String> teachers = new TreeSet<>(timetable.getTeachers());
        
        for(String s : teachers)
        {
            list.addElement(s);
        }
        QueriesTeachersAvailable.setModel(list);
        QueriesTeachersAvailable.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        QueriesTeachers.setLocationRelativeTo(null);
        QueriesTeachers.setVisible(true);
    }//GEN-LAST:event_freeTeachersBtnActionPerformed

    private void freeSlotsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeSlotsBtnActionPerformed
        QueriesOutput.setText("");
        for(int i=0;i<timetable.days.size();i++)
        {
            QueriesOutput.append("On "+dayDict[i] + "\n");
            for(int j=0;j<timetable.venues.get(i).size();j++)
            {
                for(int k=0;k<timetable.timeSlots.get(i).size();k++)
                {
                    Slot slot = timetable.days.get(i).get(new slotKey(timetable.venues.get(i).get(j),timetable.timeSlots.get(i).get(k)));
                    if(slot.isEmpty())
                        QueriesOutput.append(timetable.venues.get(i).get(j)+" "+timetable.timeSlots.get(i).get(k) + "\n");
                }
            }
            QueriesOutput.append("\n\n");
        }
    }//GEN-LAST:event_freeSlotsBtnActionPerformed

    private void freeTeachersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeTeachersBtnMouseEntered
        BtnHover(freeTeachersBtn);
    }//GEN-LAST:event_freeTeachersBtnMouseEntered

    private void freeSectionsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeSectionsBtnMouseEntered
        BtnHover(freeSectionsBtn);
    }//GEN-LAST:event_freeSectionsBtnMouseEntered

    private void freeSlotsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeSlotsBtnMouseEntered
        BtnHover(freeSlotsBtn);
    }//GEN-LAST:event_freeSlotsBtnMouseEntered

    private void freeTeachersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeTeachersBtnMouseExited
        BtnHover(freeTeachersBtn);
    }//GEN-LAST:event_freeTeachersBtnMouseExited

    private void freeSectionsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeSectionsBtnMouseExited
        BtnHover(freeSectionsBtn);
    }//GEN-LAST:event_freeSectionsBtnMouseExited

    private void freeSlotsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_freeSlotsBtnMouseExited
        BtnHover(freeSlotsBtn);
    }//GEN-LAST:event_freeSlotsBtnMouseExited

    private void TeachersButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeachersButtonMouseEntered
        BtnHover(TeachersButton);
    }//GEN-LAST:event_TeachersButtonMouseEntered

    private void TeachersButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeachersButtonMouseExited
        BtnHover(TeachersButton);
    }//GEN-LAST:event_TeachersButtonMouseExited

    private void CoursesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesButtonMouseEntered
        BtnHover(CoursesButton);
    }//GEN-LAST:event_CoursesButtonMouseEntered

    private void CoursesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoursesButtonMouseExited
        BtnHover(CoursesButton);
    }//GEN-LAST:event_CoursesButtonMouseExited

    private void SectionsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectionsButtonMouseEntered
        BtnHover(SectionsButton);
    }//GEN-LAST:event_SectionsButtonMouseEntered

    private void SectionsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SectionsButtonMouseExited
        BtnHover(SectionsButton);
    }//GEN-LAST:event_SectionsButtonMouseExited

    private void QueriesTeachersAvailableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_QueriesTeachersAvailableValueChanged
        if(!evt.getValueIsAdjusting())
            {
                List<String> Selections = QueriesTeachersAvailable.getSelectedValuesList();
                DefaultListModel selectedList = new DefaultListModel();
                for(int i=0;i<Selections.size();i++)
                {
                    selectedList.addElement(Selections.get(i));
                }
                QueriesTeachersSelected.setModel(selectedList);
                
            }
    }//GEN-LAST:event_QueriesTeachersAvailableValueChanged

    private void Createbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Createbtn3ActionPerformed
        HashSet<String> teachers = new HashSet<>(QueriesTeachersAvailable.getSelectedValuesList());
        QueriesTeachers.dispose();
        QueriesOutput.setText("");
        int count = 0;
        for(int i=0;i<timetable.days.size();i++)
        {
            QueriesOutput.append("\t "+ dayDict[i]+"\n");
            for(int j=0;j<timetable.timeSlots.get(i).size();j++)
            {
                count=0;
                for(int k=0;k<timetable.venues.get(i).size();k++)
                {
                    Slot slot = timetable.days.get(i).get(new slotKey(timetable.venues.get(i).get(k),timetable.timeSlots.get(i).get(j)));
                    if(teachers.contains(slot.getTeacher()))
                        count++;
                }
                if(count==0)
                {
                    for(String teacher : teachers)
                    {
                        QueriesOutput.append(teacher + "  ");
                    }
                    QueriesOutput.append("\nhave no classes at "+timetable.timeSlots.get(i).get(j) + "\n\n");
                }

            }
            QueriesOutput.append("\n\n");
        }
        
       
    }//GEN-LAST:event_Createbtn3ActionPerformed

    private void QueriesSectionsAvailableValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_QueriesSectionsAvailableValueChanged
        if(!evt.getValueIsAdjusting())
            {
                List<String> Selections = QueriesSectionsAvailable.getSelectedValuesList();
                DefaultListModel selectedList = new DefaultListModel();
                for(int i=0;i<Selections.size();i++)
                {
                    selectedList.addElement(Selections.get(i));
                }
                QueriesSectionsSelected.setModel(selectedList);
            }
    }//GEN-LAST:event_QueriesSectionsAvailableValueChanged

    private void Createbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Createbtn4ActionPerformed
        HashSet<String> sections = new HashSet<>(QueriesSectionsAvailable.getSelectedValuesList());
        QueriesSections.dispose();
        QueriesOutput.setText("");
        int count = 0;
        for(int i=0;i<timetable.days.size();i++)
        {
            QueriesOutput.append("\t "+ dayDict[i]+"\n");
            for(int j=0;j<timetable.timeSlots.get(i).size();j++)
            {
                count=0;
                for(int k=0;k<timetable.venues.get(i).size();k++)
                {
                    Slot slot = timetable.days.get(i).get(new slotKey(timetable.venues.get(i).get(k),timetable.timeSlots.get(i).get(j)));
                    if(sections.contains(slot.getclass()))
                        count++;
                }
                if(count==0)
                {
                    for(String section : sections)
                    {
                        QueriesOutput.append(section+ "  ");
                    }
                    QueriesOutput.append("\nhave no classes at "+timetable.timeSlots.get(i).get(j) + "\n\n");
                }

            }
            QueriesOutput.append("\n\n");
        }
    }//GEN-LAST:event_Createbtn4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ClashesDialog;
    private javax.swing.JList<String> CoursesAvailableList;
    private javax.swing.JButton CoursesButton;
    private javax.swing.JDialog CoursesDialog;
    private javax.swing.JList<String> CoursesSelectedList;
    private javax.swing.JButton Createbtn;
    private javax.swing.JButton Createbtn1;
    private javax.swing.JButton Createbtn2;
    private javax.swing.JButton Createbtn3;
    private javax.swing.JButton Createbtn4;
    private javax.swing.JTextArea Data;
    private javax.swing.JTextArea QueriesOutput;
    private javax.swing.JDialog QueriesRoom;
    private javax.swing.JDialog QueriesSections;
    private javax.swing.JList<String> QueriesSectionsAvailable;
    private javax.swing.JList<String> QueriesSectionsSelected;
    private javax.swing.JDialog QueriesTeachers;
    private javax.swing.JList<String> QueriesTeachersAvailable;
    private javax.swing.JList<String> QueriesTeachersSelected;
    private javax.swing.JButton Return;
    private javax.swing.JList<String> SectionsAvailableList;
    private javax.swing.JButton SectionsButton;
    private javax.swing.JDialog SectionsDialog;
    private javax.swing.JList<String> SectionsSelectedList;
    private javax.swing.JList<String> TeachersAvailableList;
    private javax.swing.JButton TeachersButton;
    private javax.swing.JDialog TeachersDialog;
    private javax.swing.JList<String> TeachersSelectedList;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnPanel1;
    private javax.swing.JPanel btnPanel2;
    private javax.swing.JPanel btnPanel3;
    private javax.swing.JButton freeSectionsBtn;
    private javax.swing.JButton freeSlotsBtn;
    private javax.swing.JButton freeTeachersBtn;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuQueries;
    private javax.swing.JPanel menuTimetables;
    private javax.swing.JPanel menuparent;
    private javax.swing.JButton queries;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JButton timetables;
    // End of variables declaration//GEN-END:variables
}
